# Datafiles change
contigs: contigs.txt
sample_data: samples2data.tsv
# Directories
outdir: avamb_outdir
# Module envs
moduleenvs:
  minimap2: minimap2/2.6
  samtools: samtools/1.17
# Options for minimap
minimap:
  minimap_mem: 15GB
  minimap_ppn: 15
# Options for vamb
vamb:
  avamb_mem: 15GB
  avamb_ppn: 30
  avamb_params:  --model vae-aae  -o C  --seed 0 
  avamb_preload: 

# other options - improve formatting
index_size: 3G
min_contig_size: 2000
min_bin_size: 200000
min_identity: 0.95
min_comp: 0.9
max_cont: 0.05